#!/usr/bin/env ruby
require 'json'

main = Dir.glob("cms-components.js") + Dir.glob("components/**/*.js")
data = JSON.parse(open("bower.json").read)
data["main"] = main
File.open("bower.json", "w") do |file|
  file.write(JSON.pretty_generate(data))
end
