#!/usr/bin/env ruby
main = Dir.glob("components/**/*.*").inspect
File.open("package.json", "r+") do |file|
  file.each_line do |line|
    line.gsub! /(.)*?(main:)(.*)?,/, "$1$2 #{main},"
  end
  file.write
end
